lib/tldr_event_sourcing_web/router.ex
defmodule TldrEventSourcingWeb.Router do
  use TldrEventSourcingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authorized do
    plug TldrEventSourcingWeb.Auth.Pipeline
  end

  scope "/", TldrEventSourcingWeb do
    pipe_through :browser

    scope "/" do
      pipe_through :authorized
      get "/", TicketsController, :index
      resources "/tickets", TicketsController
      post "/tickets/:ticket_id/comment", TicketsController, :add_comment
      
      get "/tickets/:ticket_id/comment/:comment_id", TicketsController, :edit_comment
      put "/tickets/:ticket_id/comment/:comment_id", TicketsController, :save_comment
      #TODO: this should NOT be a get, but a delete!
      get "/tickets/:ticket_id/comment/:comment_id/delete", TicketsController, :delete_comment

      resources "/events", EventsController
      get "/events.json", EventsController, :index_json

      resources "/tables", TablesController

      resources "/blockchain", BlockchainController
      post "/blockchain/post_transaction", BlockchainController, :post_transaction
      post "/blockchain/update_transaction_status", BlockchainController, :update_transaction_status

    end

    get "/sessions/new", SessionsController, :new
    post "/sessions/", SessionsController, :create
    get "/sessions/logout", SessionsController, :logout

  end

end

lib/tldr_event_sourcing_web/controllers/blockchain_controller.ex
defmodule TldrEventSourcingWeb.BlockchainController do
  use TldrEventSourcingWeb, :controller

  plug Guardian.Plug.EnsureAuthenticated when action in [:post_transaction, :update_transaction_status]

  alias TldrEventSourcing.{Repo}
  import Ecto.Query
  require Logger

  def index(conn, _params) do
    bts = Repo.all(TldrEventSourcing.BlockchainTransaction)
    transactions_with_index = Enum.zip(bts, 0..length(bts))
    render(conn, "index.html", transactions_with_index: transactions_with_index, address: TldrEventSourcing.BlockchainTransaction.address)
  end

  def post_transaction(conn, _params) do
    TldrEventSourcing.BlockchainTransaction.publish_hash!
    index(conn, %{})
  end

  def update_transaction_status(conn, _params) do
    TldrEventSourcing.BlockchainTransaction.update_transaction_statuses
    index(conn, %{})
  end

end

lib/tldr_event_sourcing_web/views/blockchain_view.ex
defmodule TldrEventSourcingWeb.BlockchainView do
  use TldrEventSourcingWeb, :view

end

lib/tldr_event_sourcing_web/templates/blockchain/index.html.eex
<table>
  <thead>
    <th>
      Hash
    </th>
        <th>
      Transaction ID 
    </th>
        <th>
      Status
    </th>
  </thead>
  <%= for {t, index} <- @transactions_with_index do %>
    <tr>
      <td><%= t.published_hash %></td>
      <td><%= t.transaction_id %></td>
      <td><%= t.status %></td>
    </tr>
  <%= end %>
</table>

<a href="https://whatsonchain.com/address/<%= @address%>" target="_blank" rel="noopener noreferrer">See address on WhatsOnChain</a>

<br/>

<%= only_if_logged_in @conn, "publish transactions", fn -> %>
  <%= form_for @conn, Routes.blockchain_path(@conn, :post_transaction), fn f -> %>
    <%= submit "Post transaction" %>
  <% end %>

  <%= form_for @conn, Routes.blockchain_path(@conn, :update_transaction_status), fn f -> %>
    <%= submit "Update transaction status" %>
  <% end %>
<% end %>