lib/tldr_event_sourcing_web/router.ex
defmodule TldrEventSourcingWeb.Router do
  use TldrEventSourcingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authorized do
    plug TldrEventSourcingWeb.Auth.Pipeline
  end

  scope "/", TldrEventSourcingWeb do
    pipe_through :browser

    scope "/" do
      pipe_through :authorized
      get "/", TicketsController, :index
      resources "/tickets", TicketsController
      post "/tickets/:ticket_id/comment", TicketsController, :add_comment
      
      get "/tickets/:ticket_id/comment/:comment_id", TicketsController, :edit_comment
      put "/tickets/:ticket_id/comment/:comment_id", TicketsController, :save_comment
      #TODO: this should NOT be a get, but a delete!
      get "/tickets/:ticket_id/comment/:comment_id/delete", TicketsController, :delete_comment

      resources "/events", EventsController
      get "/events.json", EventsController, :index_json

      resources "/tables", TablesController

      resources "/blockchain", BlockchainController
      post "/blockchain/post_transaction", BlockchainController, :post_transaction
      post "/blockchain/update_transaction_status", BlockchainController, :update_transaction_status

    end

    get "/sessions/new", SessionsController, :new
    post "/sessions/", SessionsController, :create
    get "/sessions/logout", SessionsController, :logout

  end

end

lib/tldr_event_sourcing/domain/ticket.ex
defmodule TldrEventSourcing.Ticket do
  use TldrEventSourcing.Schema

  import Ecto.Changeset
  alias TldrEventSourcing.{Event, Repo, Ticket, User}
  import Ecto.Query, only: [from: 2]

  @max_tickets_per_user 3

  defmodule Comment do
    use TldrEventSourcing.Schema

    schema "comments" do
      field :text, :string
      field :timestamp, :utc_datetime_usec
      belongs_to :author, User
      belongs_to :ticket, Ticket
    end
  end

  schema "tickets" do
    field :title, :string
    field :body, :string
    field :assigned_to, :binary_id
    field :is_solved, :boolean
    field :timestamp, :utc_datetime_usec
    belongs_to :author, User
    has_many :comments, Comment
  end

  def create_ticket(speaker, title, body \\ "") do
    id = Ecto.UUID.generate
    Event.emit_event(speaker, __MODULE__, :ticket_created, id, %{title: title, body: body})
    id
  end

  def assign_ticket(speaker, ticket_id, assigned_to) do
    result = Repo.transaction(fn ->
      Repo.lock_entity(User, assigned_to)

      if open_assigned_ticket_count(assigned_to) == @max_tickets_per_user do
        {:error, "too many tickets"}
      else
        Event.emit_event(speaker, __MODULE__, :ticket_assigned, ticket_id, %{assigned_to: assigned_to})
        {:ok, nil}
      end
    end)

    #Transaction wrappea
    case result do
      {:ok, value} -> value
      err -> err
    end
  end

  def solve_ticket(speaker, ticket_id) do
    Event.emit_event(speaker, __MODULE__, :ticket_solved, ticket_id, %{})
  end

  def add_comment(speaker, ticket_id, comment_text) do
    id = Ecto.UUID.generate
    Event.emit_event(speaker, __MODULE__, :comment_added, ticket_id, %{comment_id: id, text: comment_text})
    id
  end

  def edit_comment(speaker = %TldrEventSourcing.Speaker{
                      speaker_type: TldrEventSourcing.UserSpeaker,
                      speaker_id: user_id,
                    }, ticket_id, comment_id, comment_text) do
    if Repo.get_by(Comment, id: comment_id, ticket_id: ticket_id, author_id: user_id) do
      Event.emit_event(speaker, __MODULE__, :comment_edited, ticket_id, %{comment_id: comment_id, text: comment_text})
      {:ok, nil}
    else
      {:error, "no comment found"}
    end
  end

  def delete_comment(speaker = %TldrEventSourcing.Speaker{
      speaker_type: TldrEventSourcing.UserSpeaker,
      speaker_id: user_id,
    }, ticket_id, comment_id) do
    if Repo.get_by(Comment, id: comment_id, ticket_id: ticket_id, author_id: user_id) do
      Event.emit_event(speaker, __MODULE__, :comment_deleted, ticket_id, %{comment_id: comment_id})
      {:ok, nil}
    else
      {:error, "no comment found"}
    end
  end

  #Eventos
  def ticket_created(%{title: title, body: body}, %{aggregate_id: ticket_id, speaker_id: speaker_id, timestamp: timestamp}) do
    u = %Ticket{title: title, body: body, id: ticket_id, is_solved: false, author_id: speaker_id, timestamp: timestamp}
    Repo.insert(u)
  end

  def ticket_assigned(params, %{aggregate_id: ticket_id}) do
    ticket = Repo.get_by(Ticket, id: ticket_id)
    change = ticket |> cast(params, [:assigned_to])
    Repo.update(change)
  end

  def ticket_solved(%{}, %{aggregate_id: ticket_id}) do
    ticket = Repo.get_by(Ticket, id: ticket_id)
    change = change(ticket, is_solved: true)
    Repo.update(change)
  end

  def comment_added(%{comment_id: id, text: comment_text}, %{speaker_id: speaker_id, aggregate_id: ticket_id, timestamp: timestamp}) do
    comment = %Comment{id: id, ticket_id: ticket_id, text: comment_text, author_id: speaker_id, timestamp: timestamp}
    Repo.insert(comment)
  end

  def comment_edited(%{comment_id: id, text: comment_text}, %{}) do
    comment = Repo.get_by(Comment, id: id)
    change = change(comment, text: comment_text)
    Repo.update(change)
  end

  def comment_deleted(%{comment_id: id}, %{}) do
    comment = Repo.get_by(Comment, id: id)
    Repo.delete(comment)
  end

  defp open_assigned_ticket_count(assigned_to) do
    query = from t in Ticket, where: t.assigned_to == ^assigned_to and not t.is_solved
    Repo.aggregate(query, :count, :assigned_to)
  end

end

lib/tldr_event_sourcing_web/controllers/tickets_controller.ex
defmodule TldrEventSourcingWeb.TicketsController do
  use TldrEventSourcingWeb, :controller

  plug Guardian.Plug.EnsureAuthenticated when action in [:create, :add_comment, :edit_comment, :delete_comment]

  alias TldrEventSourcing.{Repo, Ticket}
  require Logger

  def index(conn, _params) do
    tickets = Repo.all(Ticket) |> Repo.preload(:author)
    render(conn, "index.html", tickets: tickets)
  end

  def show(conn, %{"id" => id}) do
    ticket = Repo.get!(Ticket, id) |> Repo.preload(:author) |> Repo.preload(comments: :author)
    render(conn, "show.html", ticket: ticket)
  end

  def create(conn, %{"title" => title}) do
    speaker = TldrEventSourcingWeb.Auth.current_speaker(conn)
    Ticket.create_ticket(speaker, title)
    index(conn, %{})
  end

  def add_comment(conn, %{"text" => text, "ticket_id" => ticket_id}) do
    speaker = TldrEventSourcingWeb.Auth.current_speaker(conn)
    Ticket.add_comment(speaker, ticket_id, text)
    show(conn, %{"id" => ticket_id})
  end

  def edit_comment(conn, %{"ticket_id" => ticket_id, "comment_id" => comment_id}) do
    comment = Repo.get!(Ticket.Comment, comment_id)    
    render(conn, "edit_comment.html", ticket_id: ticket_id, comment: comment)
  end

  def save_comment(conn, %{"text" => text, "ticket_id" => ticket_id, "comment_id" => comment_id}) do
    speaker = TldrEventSourcingWeb.Auth.current_speaker(conn)
    Ticket.edit_comment(speaker, ticket_id, comment_id, text)
    show(conn, %{"id" => ticket_id})
  end

  def delete_comment(conn, %{"ticket_id" => ticket_id, "comment_id" => comment_id}) do
    speaker = TldrEventSourcingWeb.Auth.current_speaker(conn)
    Ticket.delete_comment(speaker, ticket_id, comment_id)
    show(conn, %{"id" => ticket_id})
  end
end

lib/tldr_event_sourcing_web/views/tickets_view.ex
defmodule TldrEventSourcingWeb.TicketsView do
  use TldrEventSourcingWeb, :view
  alias TldrEventSourcingWeb.TicketsView

  def sorted_comments(ticket) do
    Enum.sort_by(ticket.comments, fn c -> DateTime.to_unix(c.timestamp) end)
  end
end

lib/tldr_event_sourcing_web/templates/tickets/edit_comment.html.eex
<%= form_for @conn, Routes.tickets_path(@conn, :edit_comment, @ticket_id, @comment.id), [{:method, :put}], fn f -> %>
  <%= text_input f, :text, value: @comment.text %>
  
  <%= submit "Edit" %>
<%= end %>

lib/tldr_event_sourcing_web/templates/tickets/index.html.eex
<%= for ticket <- @tickets do %>
  <div class="box">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= ticket.author.username %></strong>
            <br>
            <%= ticket.title %>
          </p>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
            <%= link(to: Routes.tickets_path(@conn, :show, ticket.id), class: "item-level") do %>
              <span class="icon is-small">
                <i class="fa fa-reply" aria-hidden="true"></i>
              </span>
            <% end %>
          </div>
        </nav>
      </div>
    </article>
  </div>
<% end %>

<%= only_if_logged_in @conn, "create tickets", fn -> %>
  <%= form_for @conn, Routes.tickets_path(@conn, :create), fn f -> %>
    <%= text_input f, :title %>
    <%= submit "Create" %>
  <% end %>
<% end %>

lib/tldr_event_sourcing_web/templates/tickets/show.html.eex
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= @ticket.author.username %></strong> <small><%= @ticket.timestamp %></small>
          <br>
          <h1><%= @ticket.title %></h1>

          <%= @ticket.body %>
        </p>
      </div>
    </div>
  </article>
</div>

<%= for comment <- sorted_comments(@ticket) do %>
  <div class="box">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= comment.author.username %></strong> <small><%= comment.timestamp %></small>
            <br />
            <%= comment.text %>
          </p>
        </div>
      </div>
      <%= if comment.author_id == current_user(@conn).id do %>
        <nav class="level is-mobile">
          <div class="level-left">
            <%= link(to: Routes.tickets_path(@conn, :edit_comment, @ticket.id, comment.id), class: "item-level") do %>
              <span class="icon is-small">
                <i class="fa fa-edit" aria-hidden="true"></i>
              </span>
            <% end %>
          </div>
        </nav>
        <nav class="level is-mobile">
          <div class="level-left">
            <%= link(to: Routes.tickets_path(@conn, :delete_comment, @ticket.id, comment.id), class: "item-level") do %>
              <span class="icon is-small">
                <i class="fa fa-remove" aria-hidden="true"></i>
              </span>
            <% end %>
          </div>
        </nav>
      <% end %>
    </article>
  </div>
<% end %>

<%= only_if_logged_in @conn, "add a comment", fn -> %>
  <%= form_for @conn, Routes.tickets_path(@conn, :add_comment, @ticket.id), fn f -> %>
    <%= text_input f, :text %>
    <%= submit "Add comment" %>
  <% end %>
<% end %>

<br/>

<%= link("Back", to: Routes.tickets_path(@conn, :index)) %>